version: "2"

run:
  timeout: 2m
  tests: false

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*\\.pb\\.gorm\\.go$"
      - ".*\\.gen\\.go$"

linters:
  default: none
  enable:
    - asasalint
    - bidichk
    - bodyclose
    - copyloopvar
    - durationcheck
    # - errcheck  # Too noisy with defer Close() patterns
    - errchkjson
    - errname
    # - errorlint  # Too strict for now
    # - goconst  # Not working well with v2
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    # - staticcheck  # ST1005 can't be excluded in v2
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    goconst:
      min-len: 5
      min-occurrences: 5
    gocritic:
      disabled-checks:
        - ifElseChain  # if-else is often clearer than switch for boolean conditions
    misspell:
      locale: US
      ignore-words:
        - fullset
        - FULLSET
  exclusions:
    paths:
      - ".*\\.pb\\.go$"
      - ".*\\.pb\\.gorm\\.go$"
      - ".*\\.gen\\.go$"
      - "testing\\.go$"

