// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/rslbot/rbapi.proto

package rbapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Service_AdminAddLicenseKey_FullMethodName          = "/rslbot.api.Service/AdminAddLicenseKey"
	Service_AdminGetActiveUsers_FullMethodName         = "/rslbot.api.Service/AdminGetActiveUsers"
	Service_AdminRevokeLicense_FullMethodName          = "/rslbot.api.Service/AdminRevokeLicense"
	Service_AdminSearchDatabase_FullMethodName         = "/rslbot.api.Service/AdminSearchDatabase"
	Service_PaymentCreatePayPalCheckout_FullMethodName = "/rslbot.api.Service/PaymentCreatePayPalCheckout"
	Service_ToolStatus_FullMethodName                  = "/rslbot.api.Service/ToolStatus"
	Service_UserGetLicenses_FullMethodName             = "/rslbot.api.Service/UserGetLicenses"
	Service_UserGetSession_FullMethodName              = "/rslbot.api.Service/UserGetSession"
	Service_UserLogout_FullMethodName                  = "/rslbot.api.Service/UserLogout"
	Service_UserSyncDiscordRole_FullMethodName         = "/rslbot.api.Service/UserSyncDiscordRole"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	AdminAddLicenseKey(ctx context.Context, in *AdminAddLicenseKey_Input, opts ...grpc.CallOption) (*AdminAddLicenseKey_Output, error)
	AdminGetActiveUsers(ctx context.Context, in *AdminGetActiveUsers_Input, opts ...grpc.CallOption) (*AdminGetActiveUsers_Output, error)
	AdminRevokeLicense(ctx context.Context, in *AdminRevokeLicense_Input, opts ...grpc.CallOption) (*AdminRevokeLicense_Output, error)
	AdminSearchDatabase(ctx context.Context, in *AdminSearchDatabase_Input, opts ...grpc.CallOption) (*AdminSearchDatabase_Output, error)
	PaymentCreatePayPalCheckout(ctx context.Context, in *PaymentCreatePayPalCheckout_Input, opts ...grpc.CallOption) (*PaymentCreatePayPalCheckout_Output, error)
	ToolStatus(ctx context.Context, in *ToolStatus_Input, opts ...grpc.CallOption) (*ToolStatus_Output, error)
	UserGetLicenses(ctx context.Context, in *UserGetLicenses_Input, opts ...grpc.CallOption) (*UserGetLicenses_Output, error)
	UserGetSession(ctx context.Context, in *UserGetSession_Input, opts ...grpc.CallOption) (*UserGetSession_Output, error)
	UserLogout(ctx context.Context, in *UserLogout_Input, opts ...grpc.CallOption) (*UserLogout_Output, error)
	UserSyncDiscordRole(ctx context.Context, in *UserSyncDiscordRole_Input, opts ...grpc.CallOption) (*UserSyncDiscordRole_Output, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) AdminAddLicenseKey(ctx context.Context, in *AdminAddLicenseKey_Input, opts ...grpc.CallOption) (*AdminAddLicenseKey_Output, error) {
	out := new(AdminAddLicenseKey_Output)
	err := c.cc.Invoke(ctx, Service_AdminAddLicenseKey_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AdminGetActiveUsers(ctx context.Context, in *AdminGetActiveUsers_Input, opts ...grpc.CallOption) (*AdminGetActiveUsers_Output, error) {
	out := new(AdminGetActiveUsers_Output)
	err := c.cc.Invoke(ctx, Service_AdminGetActiveUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AdminRevokeLicense(ctx context.Context, in *AdminRevokeLicense_Input, opts ...grpc.CallOption) (*AdminRevokeLicense_Output, error) {
	out := new(AdminRevokeLicense_Output)
	err := c.cc.Invoke(ctx, Service_AdminRevokeLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AdminSearchDatabase(ctx context.Context, in *AdminSearchDatabase_Input, opts ...grpc.CallOption) (*AdminSearchDatabase_Output, error) {
	out := new(AdminSearchDatabase_Output)
	err := c.cc.Invoke(ctx, Service_AdminSearchDatabase_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) PaymentCreatePayPalCheckout(ctx context.Context, in *PaymentCreatePayPalCheckout_Input, opts ...grpc.CallOption) (*PaymentCreatePayPalCheckout_Output, error) {
	out := new(PaymentCreatePayPalCheckout_Output)
	err := c.cc.Invoke(ctx, Service_PaymentCreatePayPalCheckout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ToolStatus(ctx context.Context, in *ToolStatus_Input, opts ...grpc.CallOption) (*ToolStatus_Output, error) {
	out := new(ToolStatus_Output)
	err := c.cc.Invoke(ctx, Service_ToolStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UserGetLicenses(ctx context.Context, in *UserGetLicenses_Input, opts ...grpc.CallOption) (*UserGetLicenses_Output, error) {
	out := new(UserGetLicenses_Output)
	err := c.cc.Invoke(ctx, Service_UserGetLicenses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UserGetSession(ctx context.Context, in *UserGetSession_Input, opts ...grpc.CallOption) (*UserGetSession_Output, error) {
	out := new(UserGetSession_Output)
	err := c.cc.Invoke(ctx, Service_UserGetSession_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UserLogout(ctx context.Context, in *UserLogout_Input, opts ...grpc.CallOption) (*UserLogout_Output, error) {
	out := new(UserLogout_Output)
	err := c.cc.Invoke(ctx, Service_UserLogout_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UserSyncDiscordRole(ctx context.Context, in *UserSyncDiscordRole_Input, opts ...grpc.CallOption) (*UserSyncDiscordRole_Output, error) {
	out := new(UserSyncDiscordRole_Output)
	err := c.cc.Invoke(ctx, Service_UserSyncDiscordRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	AdminAddLicenseKey(context.Context, *AdminAddLicenseKey_Input) (*AdminAddLicenseKey_Output, error)
	AdminGetActiveUsers(context.Context, *AdminGetActiveUsers_Input) (*AdminGetActiveUsers_Output, error)
	AdminRevokeLicense(context.Context, *AdminRevokeLicense_Input) (*AdminRevokeLicense_Output, error)
	AdminSearchDatabase(context.Context, *AdminSearchDatabase_Input) (*AdminSearchDatabase_Output, error)
	PaymentCreatePayPalCheckout(context.Context, *PaymentCreatePayPalCheckout_Input) (*PaymentCreatePayPalCheckout_Output, error)
	ToolStatus(context.Context, *ToolStatus_Input) (*ToolStatus_Output, error)
	UserGetLicenses(context.Context, *UserGetLicenses_Input) (*UserGetLicenses_Output, error)
	UserGetSession(context.Context, *UserGetSession_Input) (*UserGetSession_Output, error)
	UserLogout(context.Context, *UserLogout_Input) (*UserLogout_Output, error)
	UserSyncDiscordRole(context.Context, *UserSyncDiscordRole_Input) (*UserSyncDiscordRole_Output, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) AdminAddLicenseKey(context.Context, *AdminAddLicenseKey_Input) (*AdminAddLicenseKey_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminAddLicenseKey not implemented")
}
func (UnimplementedServiceServer) AdminGetActiveUsers(context.Context, *AdminGetActiveUsers_Input) (*AdminGetActiveUsers_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminGetActiveUsers not implemented")
}
func (UnimplementedServiceServer) AdminRevokeLicense(context.Context, *AdminRevokeLicense_Input) (*AdminRevokeLicense_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRevokeLicense not implemented")
}
func (UnimplementedServiceServer) AdminSearchDatabase(context.Context, *AdminSearchDatabase_Input) (*AdminSearchDatabase_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminSearchDatabase not implemented")
}
func (UnimplementedServiceServer) PaymentCreatePayPalCheckout(context.Context, *PaymentCreatePayPalCheckout_Input) (*PaymentCreatePayPalCheckout_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PaymentCreatePayPalCheckout not implemented")
}
func (UnimplementedServiceServer) ToolStatus(context.Context, *ToolStatus_Input) (*ToolStatus_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToolStatus not implemented")
}
func (UnimplementedServiceServer) UserGetLicenses(context.Context, *UserGetLicenses_Input) (*UserGetLicenses_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetLicenses not implemented")
}
func (UnimplementedServiceServer) UserGetSession(context.Context, *UserGetSession_Input) (*UserGetSession_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserGetSession not implemented")
}
func (UnimplementedServiceServer) UserLogout(context.Context, *UserLogout_Input) (*UserLogout_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserLogout not implemented")
}
func (UnimplementedServiceServer) UserSyncDiscordRole(context.Context, *UserSyncDiscordRole_Input) (*UserSyncDiscordRole_Output, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserSyncDiscordRole not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_AdminAddLicenseKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminAddLicenseKey_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AdminAddLicenseKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AdminAddLicenseKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AdminAddLicenseKey(ctx, req.(*AdminAddLicenseKey_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AdminGetActiveUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminGetActiveUsers_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AdminGetActiveUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AdminGetActiveUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AdminGetActiveUsers(ctx, req.(*AdminGetActiveUsers_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AdminRevokeLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRevokeLicense_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AdminRevokeLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AdminRevokeLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AdminRevokeLicense(ctx, req.(*AdminRevokeLicense_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AdminSearchDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminSearchDatabase_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AdminSearchDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AdminSearchDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AdminSearchDatabase(ctx, req.(*AdminSearchDatabase_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_PaymentCreatePayPalCheckout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PaymentCreatePayPalCheckout_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).PaymentCreatePayPalCheckout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_PaymentCreatePayPalCheckout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).PaymentCreatePayPalCheckout(ctx, req.(*PaymentCreatePayPalCheckout_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ToolStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToolStatus_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ToolStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ToolStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ToolStatus(ctx, req.(*ToolStatus_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UserGetLicenses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetLicenses_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UserGetLicenses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UserGetLicenses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UserGetLicenses(ctx, req.(*UserGetLicenses_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UserGetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserGetSession_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UserGetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UserGetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UserGetSession(ctx, req.(*UserGetSession_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UserLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLogout_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UserLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UserLogout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UserLogout(ctx, req.(*UserLogout_Input))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UserSyncDiscordRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSyncDiscordRole_Input)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UserSyncDiscordRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UserSyncDiscordRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UserSyncDiscordRole(ctx, req.(*UserSyncDiscordRole_Input))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rslbot.api.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminAddLicenseKey",
			Handler:    _Service_AdminAddLicenseKey_Handler,
		},
		{
			MethodName: "AdminGetActiveUsers",
			Handler:    _Service_AdminGetActiveUsers_Handler,
		},
		{
			MethodName: "AdminRevokeLicense",
			Handler:    _Service_AdminRevokeLicense_Handler,
		},
		{
			MethodName: "AdminSearchDatabase",
			Handler:    _Service_AdminSearchDatabase_Handler,
		},
		{
			MethodName: "PaymentCreatePayPalCheckout",
			Handler:    _Service_PaymentCreatePayPalCheckout_Handler,
		},
		{
			MethodName: "ToolStatus",
			Handler:    _Service_ToolStatus_Handler,
		},
		{
			MethodName: "UserGetLicenses",
			Handler:    _Service_UserGetLicenses_Handler,
		},
		{
			MethodName: "UserGetSession",
			Handler:    _Service_UserGetSession_Handler,
		},
		{
			MethodName: "UserLogout",
			Handler:    _Service_UserLogout_Handler,
		},
		{
			MethodName: "UserSyncDiscordRole",
			Handler:    _Service_UserSyncDiscordRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rslbot/rbapi.proto",
}
