// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        (unknown)
// source: proto/rslbot/rbapi.proto

package rbapi

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	_ "rslbot.com/go/pkg/errcode"
	rbdb "rslbot.com/go/pkg/rbdb"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminAddLicenseKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminAddLicenseKey) Reset() {
	*x = AdminAddLicenseKey{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAddLicenseKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddLicenseKey) ProtoMessage() {}

func (x *AdminAddLicenseKey) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddLicenseKey.ProtoReflect.Descriptor instead.
func (*AdminAddLicenseKey) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{0}
}

type AdminGetActiveUsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminGetActiveUsers) Reset() {
	*x = AdminGetActiveUsers{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetActiveUsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetActiveUsers) ProtoMessage() {}

func (x *AdminGetActiveUsers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetActiveUsers.ProtoReflect.Descriptor instead.
func (*AdminGetActiveUsers) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{1}
}

type AdminRevokeLicense struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminRevokeLicense) Reset() {
	*x = AdminRevokeLicense{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRevokeLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRevokeLicense) ProtoMessage() {}

func (x *AdminRevokeLicense) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRevokeLicense.ProtoReflect.Descriptor instead.
func (*AdminRevokeLicense) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{2}
}

type AdminSearchDatabase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminSearchDatabase) Reset() {
	*x = AdminSearchDatabase{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSearchDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchDatabase) ProtoMessage() {}

func (x *AdminSearchDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchDatabase.ProtoReflect.Descriptor instead.
func (*AdminSearchDatabase) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{3}
}

type PaymentCreatePayPalCheckout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaymentCreatePayPalCheckout) Reset() {
	*x = PaymentCreatePayPalCheckout{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreatePayPalCheckout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreatePayPalCheckout) ProtoMessage() {}

func (x *PaymentCreatePayPalCheckout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreatePayPalCheckout.ProtoReflect.Descriptor instead.
func (*PaymentCreatePayPalCheckout) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{4}
}

type ToolStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToolStatus) Reset() {
	*x = ToolStatus{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus) ProtoMessage() {}

func (x *ToolStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus.ProtoReflect.Descriptor instead.
func (*ToolStatus) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{5}
}

type UserGetLicenses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetLicenses) Reset() {
	*x = UserGetLicenses{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetLicenses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetLicenses) ProtoMessage() {}

func (x *UserGetLicenses) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetLicenses.ProtoReflect.Descriptor instead.
func (*UserGetLicenses) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{6}
}

type UserGetSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetSession) Reset() {
	*x = UserGetSession{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetSession) ProtoMessage() {}

func (x *UserGetSession) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetSession.ProtoReflect.Descriptor instead.
func (*UserGetSession) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{7}
}

type UserLogout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserLogout) Reset() {
	*x = UserLogout{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogout) ProtoMessage() {}

func (x *UserLogout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogout.ProtoReflect.Descriptor instead.
func (*UserLogout) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{8}
}

type UserSyncDiscordRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSyncDiscordRole) Reset() {
	*x = UserSyncDiscordRole{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSyncDiscordRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSyncDiscordRole) ProtoMessage() {}

func (x *UserSyncDiscordRole) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSyncDiscordRole.ProtoReflect.Descriptor instead.
func (*UserSyncDiscordRole) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{9}
}

type AdminAddLicenseKey_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    int64                    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail string                   `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Duration  rbdb.LicenseKey_Duration `protobuf:"varint,3,opt,name=duration,proto3,enum=rslbot.db.LicenseKey_Duration" json:"duration,omitempty"`
	Tier      rbdb.LicenseKey_Tier     `protobuf:"varint,4,opt,name=tier,proto3,enum=rslbot.db.LicenseKey_Tier" json:"tier,omitempty"`
}

func (x *AdminAddLicenseKey_Input) Reset() {
	*x = AdminAddLicenseKey_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAddLicenseKey_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddLicenseKey_Input) ProtoMessage() {}

func (x *AdminAddLicenseKey_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddLicenseKey_Input.ProtoReflect.Descriptor instead.
func (*AdminAddLicenseKey_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AdminAddLicenseKey_Input) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AdminAddLicenseKey_Input) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *AdminAddLicenseKey_Input) GetDuration() rbdb.LicenseKey_Duration {
	if x != nil {
		return x.Duration
	}
	return rbdb.LicenseKey_Duration(0)
}

func (x *AdminAddLicenseKey_Input) GetTier() rbdb.LicenseKey_Tier {
	if x != nil {
		return x.Tier
	}
	return rbdb.LicenseKey_Tier(0)
}

type AdminAddLicenseKey_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LicenseKey *rbdb.LicenseKey `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
}

func (x *AdminAddLicenseKey_Output) Reset() {
	*x = AdminAddLicenseKey_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAddLicenseKey_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAddLicenseKey_Output) ProtoMessage() {}

func (x *AdminAddLicenseKey_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAddLicenseKey_Output.ProtoReflect.Descriptor instead.
func (*AdminAddLicenseKey_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AdminAddLicenseKey_Output) GetLicenseKey() *rbdb.LicenseKey {
	if x != nil {
		return x.LicenseKey
	}
	return nil
}

type AdminGetActiveUsers_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminGetActiveUsers_Input) Reset() {
	*x = AdminGetActiveUsers_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetActiveUsers_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetActiveUsers_Input) ProtoMessage() {}

func (x *AdminGetActiveUsers_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetActiveUsers_Input.ProtoReflect.Descriptor instead.
func (*AdminGetActiveUsers_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{1, 0}
}

type AdminGetActiveUsers_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FreeTier   int32 `protobuf:"varint,1,opt,name=free_tier,json=freeTier,proto3" json:"free_tier,omitempty"`
	PaidTier   int32 `protobuf:"varint,2,opt,name=paid_tier,json=paidTier,proto3" json:"paid_tier,omitempty"`
	TotalUsers int32 `protobuf:"varint,3,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
}

func (x *AdminGetActiveUsers_Output) Reset() {
	*x = AdminGetActiveUsers_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminGetActiveUsers_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminGetActiveUsers_Output) ProtoMessage() {}

func (x *AdminGetActiveUsers_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminGetActiveUsers_Output.ProtoReflect.Descriptor instead.
func (*AdminGetActiveUsers_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{1, 1}
}

func (x *AdminGetActiveUsers_Output) GetFreeTier() int32 {
	if x != nil {
		return x.FreeTier
	}
	return 0
}

func (x *AdminGetActiveUsers_Output) GetPaidTier() int32 {
	if x != nil {
		return x.PaidTier
	}
	return 0
}

func (x *AdminGetActiveUsers_Output) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

type AdminRevokeLicense_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *AdminRevokeLicense_Input) Reset() {
	*x = AdminRevokeLicense_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRevokeLicense_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRevokeLicense_Input) ProtoMessage() {}

func (x *AdminRevokeLicense_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRevokeLicense_Input.ProtoReflect.Descriptor instead.
func (*AdminRevokeLicense_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AdminRevokeLicense_Input) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AdminRevokeLicense_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LicenseKey *rbdb.LicenseKey `protobuf:"bytes,1,opt,name=license_key,json=licenseKey,proto3" json:"license_key,omitempty"`
}

func (x *AdminRevokeLicense_Output) Reset() {
	*x = AdminRevokeLicense_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRevokeLicense_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRevokeLicense_Output) ProtoMessage() {}

func (x *AdminRevokeLicense_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRevokeLicense_Output.ProtoReflect.Descriptor instead.
func (*AdminRevokeLicense_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{2, 1}
}

func (x *AdminRevokeLicense_Output) GetLicenseKey() *rbdb.LicenseKey {
	if x != nil {
		return x.LicenseKey
	}
	return nil
}

type AdminSearchDatabase_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchTerm string `protobuf:"bytes,1,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
}

func (x *AdminSearchDatabase_Input) Reset() {
	*x = AdminSearchDatabase_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSearchDatabase_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchDatabase_Input) ProtoMessage() {}

func (x *AdminSearchDatabase_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchDatabase_Input.ProtoReflect.Descriptor instead.
func (*AdminSearchDatabase_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AdminSearchDatabase_Input) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type AdminSearchDatabase_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users         []*rbdb.User         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	LicenseKeys   []*rbdb.LicenseKey   `protobuf:"bytes,2,rep,name=license_keys,json=licenseKeys,proto3" json:"license_keys,omitempty"`
	Payments      []*rbdb.Payment      `protobuf:"bytes,3,rep,name=payments,proto3" json:"payments,omitempty"`
	Subscriptions []*rbdb.Subscription `protobuf:"bytes,4,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
}

func (x *AdminSearchDatabase_Output) Reset() {
	*x = AdminSearchDatabase_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSearchDatabase_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSearchDatabase_Output) ProtoMessage() {}

func (x *AdminSearchDatabase_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSearchDatabase_Output.ProtoReflect.Descriptor instead.
func (*AdminSearchDatabase_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AdminSearchDatabase_Output) GetUsers() []*rbdb.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *AdminSearchDatabase_Output) GetLicenseKeys() []*rbdb.LicenseKey {
	if x != nil {
		return x.LicenseKeys
	}
	return nil
}

func (x *AdminSearchDatabase_Output) GetPayments() []*rbdb.Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *AdminSearchDatabase_Output) GetSubscriptions() []*rbdb.Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

type PaymentCreatePayPalCheckout_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LicenseDuration rbdb.LicenseKey_Duration `protobuf:"varint,1,opt,name=license_duration,json=licenseDuration,proto3,enum=rslbot.db.LicenseKey_Duration" json:"license_duration,omitempty"`
	RenewalKeyId    int64                    `protobuf:"varint,2,opt,name=renewal_key_id,json=renewalKeyId,proto3" json:"renewal_key_id,omitempty"`
}

func (x *PaymentCreatePayPalCheckout_Input) Reset() {
	*x = PaymentCreatePayPalCheckout_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreatePayPalCheckout_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreatePayPalCheckout_Input) ProtoMessage() {}

func (x *PaymentCreatePayPalCheckout_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreatePayPalCheckout_Input.ProtoReflect.Descriptor instead.
func (*PaymentCreatePayPalCheckout_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PaymentCreatePayPalCheckout_Input) GetLicenseDuration() rbdb.LicenseKey_Duration {
	if x != nil {
		return x.LicenseDuration
	}
	return rbdb.LicenseKey_Duration(0)
}

func (x *PaymentCreatePayPalCheckout_Input) GetRenewalKeyId() int64 {
	if x != nil {
		return x.RenewalKeyId
	}
	return 0
}

type PaymentCreatePayPalCheckout_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId     string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CheckoutUrl string `protobuf:"bytes,2,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
}

func (x *PaymentCreatePayPalCheckout_Output) Reset() {
	*x = PaymentCreatePayPalCheckout_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentCreatePayPalCheckout_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentCreatePayPalCheckout_Output) ProtoMessage() {}

func (x *PaymentCreatePayPalCheckout_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentCreatePayPalCheckout_Output.ProtoReflect.Descriptor instead.
func (*PaymentCreatePayPalCheckout_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{4, 1}
}

func (x *PaymentCreatePayPalCheckout_Output) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentCreatePayPalCheckout_Output) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type ToolStatus_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToolStatus_Input) Reset() {
	*x = ToolStatus_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus_Input) ProtoMessage() {}

func (x *ToolStatus_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus_Input.ProtoReflect.Descriptor instead.
func (*ToolStatus_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{5, 0}
}

type ToolStatus_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EverythingIsOk bool `protobuf:"varint,1,opt,name=everything_is_ok,json=everythingIsOk,proto3" json:"everything_is_ok,omitempty"`
}

func (x *ToolStatus_Output) Reset() {
	*x = ToolStatus_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolStatus_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolStatus_Output) ProtoMessage() {}

func (x *ToolStatus_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolStatus_Output.ProtoReflect.Descriptor instead.
func (*ToolStatus_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{5, 1}
}

func (x *ToolStatus_Output) GetEverythingIsOk() bool {
	if x != nil {
		return x.EverythingIsOk
	}
	return false
}

type UserGetLicenses_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetLicenses_Input) Reset() {
	*x = UserGetLicenses_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetLicenses_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetLicenses_Input) ProtoMessage() {}

func (x *UserGetLicenses_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetLicenses_Input.ProtoReflect.Descriptor instead.
func (*UserGetLicenses_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{6, 0}
}

type UserGetLicenses_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Licenses []*rbdb.LicenseKey `protobuf:"bytes,1,rep,name=licenses,proto3" json:"licenses,omitempty"`
}

func (x *UserGetLicenses_Output) Reset() {
	*x = UserGetLicenses_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetLicenses_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetLicenses_Output) ProtoMessage() {}

func (x *UserGetLicenses_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetLicenses_Output.ProtoReflect.Descriptor instead.
func (*UserGetLicenses_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{6, 1}
}

func (x *UserGetLicenses_Output) GetLicenses() []*rbdb.LicenseKey {
	if x != nil {
		return x.Licenses
	}
	return nil
}

type UserGetSession_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserGetSession_Input) Reset() {
	*x = UserGetSession_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetSession_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetSession_Input) ProtoMessage() {}

func (x *UserGetSession_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetSession_Input.ProtoReflect.Descriptor instead.
func (*UserGetSession_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{7, 0}
}

type UserGetSession_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *rbdb.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UserGetSession_Output) Reset() {
	*x = UserGetSession_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserGetSession_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserGetSession_Output) ProtoMessage() {}

func (x *UserGetSession_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserGetSession_Output.ProtoReflect.Descriptor instead.
func (*UserGetSession_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{7, 1}
}

func (x *UserGetSession_Output) GetUser() *rbdb.User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserLogout_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserLogout_Input) Reset() {
	*x = UserLogout_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogout_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogout_Input) ProtoMessage() {}

func (x *UserLogout_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogout_Input.ProtoReflect.Descriptor instead.
func (*UserLogout_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{8, 0}
}

type UserLogout_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UserLogout_Output) Reset() {
	*x = UserLogout_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLogout_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLogout_Output) ProtoMessage() {}

func (x *UserLogout_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLogout_Output.ProtoReflect.Descriptor instead.
func (*UserLogout_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{8, 1}
}

func (x *UserLogout_Output) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UserSyncDiscordRole_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserSyncDiscordRole_Input) Reset() {
	*x = UserSyncDiscordRole_Input{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSyncDiscordRole_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSyncDiscordRole_Input) ProtoMessage() {}

func (x *UserSyncDiscordRole_Input) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSyncDiscordRole_Input.ProtoReflect.Descriptor instead.
func (*UserSyncDiscordRole_Input) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{9, 0}
}

type UserSyncDiscordRole_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success            bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message            string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	HasLifetimeLicense bool   `protobuf:"varint,3,opt,name=has_lifetime_license,json=hasLifetimeLicense,proto3" json:"has_lifetime_license,omitempty"`
	DiscordLinked      bool   `protobuf:"varint,4,opt,name=discord_linked,json=discordLinked,proto3" json:"discord_linked,omitempty"`
	RoleAssigned       bool   `protobuf:"varint,5,opt,name=role_assigned,json=roleAssigned,proto3" json:"role_assigned,omitempty"`
}

func (x *UserSyncDiscordRole_Output) Reset() {
	*x = UserSyncDiscordRole_Output{}
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSyncDiscordRole_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSyncDiscordRole_Output) ProtoMessage() {}

func (x *UserSyncDiscordRole_Output) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rslbot_rbapi_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSyncDiscordRole_Output.ProtoReflect.Descriptor instead.
func (*UserSyncDiscordRole_Output) Descriptor() ([]byte, []int) {
	return file_proto_rslbot_rbapi_proto_rawDescGZIP(), []int{9, 1}
}

func (x *UserSyncDiscordRole_Output) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UserSyncDiscordRole_Output) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UserSyncDiscordRole_Output) GetHasLifetimeLicense() bool {
	if x != nil {
		return x.HasLifetimeLicense
	}
	return false
}

func (x *UserSyncDiscordRole_Output) GetDiscordLinked() bool {
	if x != nil {
		return x.DiscordLinked
	}
	return false
}

func (x *UserSyncDiscordRole_Output) GetRoleAssigned() bool {
	if x != nil {
		return x.RoleAssigned
	}
	return false
}

var File_proto_rslbot_rbapi_proto protoreflect.FileDescriptor

var file_proto_rslbot_rbapi_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2f, 0x72,
	0x62, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x72, 0x73, 0x6c, 0x62,
	0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2f, 0x72, 0x62, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2f, 0x65, 0x72, 0x72,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x02, 0x0a, 0x12, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65,
	0x79, 0x1a, 0xab, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x3a, 0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64,
	0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x2e, 0x44, 0x75, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2e, 0x0a, 0x04, 0x74, 0x69, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1a, 0x2e,
	0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x4b, 0x65, 0x79, 0x2e, 0x54, 0x69, 0x65, 0x72, 0x52, 0x04, 0x74, 0x69, 0x65, 0x72, 0x1a,
	0x40, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x6c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e,
	0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0a, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65,
	0x79, 0x22, 0x83, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x1a, 0x07, 0x0a, 0x05, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x63, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x72, 0x65, 0x65, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x66, 0x72, 0x65, 0x65, 0x54, 0x69, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x69,
	0x64, 0x5f, 0x74, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x69, 0x64, 0x54, 0x69, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x55, 0x73, 0x65, 0x72, 0x73, 0x22, 0x71, 0x0a, 0x12, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x1a, 0x19, 0x0a,
	0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x1a, 0x40, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x36, 0x0a, 0x0b, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74,
	0x2e, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0a,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x9a, 0x02, 0x0a, 0x13, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x1a, 0x28, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x72, 0x6d, 0x1a, 0xd8, 0x01, 0x0a,
	0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x25, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e,
	0x64, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x38,
	0x0a, 0x0c, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62,
	0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x0b, 0x6c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x2e, 0x0a, 0x08, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x72, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3d, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xdf, 0x01, 0x0a, 0x1b, 0x50, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x50, 0x61, 0x6c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x1a, 0x78, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x49, 0x0a, 0x10, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x72, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65,
	0x79, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0f, 0x6c, 0x69, 0x63, 0x65,
	0x6e, 0x73, 0x65, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x72,
	0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x5f, 0x6b, 0x65, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65, 0x6e, 0x65, 0x77, 0x61, 0x6c, 0x4b, 0x65, 0x79, 0x49,
	0x64, 0x1a, 0x46, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x6f,
	0x75, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x49, 0x0a, 0x0a, 0x54, 0x6f, 0x6f,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x07, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x32, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x76,
	0x65, 0x72, 0x79, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x73, 0x5f, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x65, 0x76, 0x65, 0x72, 0x79, 0x74, 0x68, 0x69, 0x6e, 0x67,
	0x49, 0x73, 0x4f, 0x6b, 0x22, 0x57, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x1a, 0x07, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x3b, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x31, 0x0a, 0x08, 0x6c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72,
	0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x08, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x48, 0x0a,
	0x0e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x1a,
	0x07, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2d, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x64, 0x62, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x1a, 0x07, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x22,
	0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x44,
	0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x07, 0x0a, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x1a, 0xba, 0x01, 0x0a, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x12, 0x68, 0x61, 0x73, 0x4c, 0x69, 0x66, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x4c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72,
	0x6f, 0x6c, 0x65, 0x5f, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0c, 0x72, 0x6f, 0x6c, 0x65, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x32, 0xf8, 0x09, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x84, 0x01, 0x0a,
	0x12, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x24, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x4b, 0x65, 0x79, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x73, 0x6c, 0x62,
	0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x41, 0x64, 0x64, 0x4c,
	0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4b, 0x65, 0x79, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x64,
	0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x64, 0x64, 0x2d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x2d,
	0x6b, 0x65, 0x79, 0x12, 0x81, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x25, 0x2e, 0x72, 0x73,
	0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65,
	0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x41, 0x64, 0x6d, 0x69, 0x6e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x15, 0x12, 0x13, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x2d, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x87, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x24,
	0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x76, 0x6f, 0x6b, 0x65, 0x4c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x24, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x1e, 0x3a, 0x01, 0x2a, 0x22, 0x19, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x72,
	0x65, 0x76, 0x6f, 0x6b, 0x65, 0x2d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x2d, 0x6b, 0x65,
	0x79, 0x12, 0x87, 0x01, 0x0a, 0x13, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x25, 0x2e, 0x72, 0x73, 0x6c, 0x62,
	0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x26, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73,
	0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b,
	0x3a, 0x01, 0x2a, 0x22, 0x16, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2f, 0x73, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x2d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0xa8, 0x01, 0x0a, 0x1b,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79,
	0x50, 0x61, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x2d, 0x2e, 0x72, 0x73,
	0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x50, 0x61, 0x6c, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x6f, 0x75, 0x74, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x2e, 0x2e, 0x72, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x50, 0x61, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x2a, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x24, 0x3a, 0x01, 0x2a, 0x22, 0x1f, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x61, 0x79, 0x70, 0x61, 0x6c, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2d, 0x63, 0x68,
	0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x12, 0x5a, 0x0a, 0x0a, 0x54, 0x6f, 0x6f, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x1d, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x54, 0x6f, 0x6f, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x70, 0x0a, 0x0f, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x73, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x22, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x63,
	0x65, 0x6e, 0x73, 0x65, 0x73, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x16, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x63, 0x65,
	0x6e, 0x73, 0x65, 0x73, 0x12, 0x6c, 0x0a, 0x0e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x21, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x47, 0x65, 0x74, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x15, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x5f, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74,
	0x12, 0x1c, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1d,
	0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x14, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x0c, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x6c, 0x6f, 0x67,
	0x6f, 0x75, 0x74, 0x12, 0x85, 0x01, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x25, 0x2e, 0x72, 0x73,
	0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e,
	0x63, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x2e, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x1a, 0x26, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x52,
	0x6f, 0x6c, 0x65, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x19, 0x22, 0x17, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x2d, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x2d, 0x72, 0x6f, 0x6c, 0x65, 0x42, 0x7e, 0x0a, 0x0e, 0x63,
	0x6f, 0x6d, 0x2e, 0x72, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x42, 0x0a, 0x52,
	0x62, 0x61, 0x70, 0x69, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x17, 0x72, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72,
	0x62, 0x61, 0x70, 0x69, 0xa2, 0x02, 0x03, 0x52, 0x41, 0x58, 0xaa, 0x02, 0x0a, 0x52, 0x73, 0x6c,
	0x62, 0x6f, 0x74, 0x2e, 0x41, 0x70, 0x69, 0xca, 0x02, 0x0a, 0x52, 0x73, 0x6c, 0x62, 0x6f, 0x74,
	0x5c, 0x41, 0x70, 0x69, 0xe2, 0x02, 0x16, 0x52, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x5c, 0x41, 0x70,
	0x69, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0b,
	0x52, 0x73, 0x6c, 0x62, 0x6f, 0x74, 0x3a, 0x3a, 0x41, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_rslbot_rbapi_proto_rawDescOnce sync.Once
	file_proto_rslbot_rbapi_proto_rawDescData = file_proto_rslbot_rbapi_proto_rawDesc
)

func file_proto_rslbot_rbapi_proto_rawDescGZIP() []byte {
	file_proto_rslbot_rbapi_proto_rawDescOnce.Do(func() {
		file_proto_rslbot_rbapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rslbot_rbapi_proto_rawDescData)
	})
	return file_proto_rslbot_rbapi_proto_rawDescData
}

var file_proto_rslbot_rbapi_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_proto_rslbot_rbapi_proto_goTypes = []any{
	(*AdminAddLicenseKey)(nil),                 // 0: rslbot.api.AdminAddLicenseKey
	(*AdminGetActiveUsers)(nil),                // 1: rslbot.api.AdminGetActiveUsers
	(*AdminRevokeLicense)(nil),                 // 2: rslbot.api.AdminRevokeLicense
	(*AdminSearchDatabase)(nil),                // 3: rslbot.api.AdminSearchDatabase
	(*PaymentCreatePayPalCheckout)(nil),        // 4: rslbot.api.PaymentCreatePayPalCheckout
	(*ToolStatus)(nil),                         // 5: rslbot.api.ToolStatus
	(*UserGetLicenses)(nil),                    // 6: rslbot.api.UserGetLicenses
	(*UserGetSession)(nil),                     // 7: rslbot.api.UserGetSession
	(*UserLogout)(nil),                         // 8: rslbot.api.UserLogout
	(*UserSyncDiscordRole)(nil),                // 9: rslbot.api.UserSyncDiscordRole
	(*AdminAddLicenseKey_Input)(nil),           // 10: rslbot.api.AdminAddLicenseKey.Input
	(*AdminAddLicenseKey_Output)(nil),          // 11: rslbot.api.AdminAddLicenseKey.Output
	(*AdminGetActiveUsers_Input)(nil),          // 12: rslbot.api.AdminGetActiveUsers.Input
	(*AdminGetActiveUsers_Output)(nil),         // 13: rslbot.api.AdminGetActiveUsers.Output
	(*AdminRevokeLicense_Input)(nil),           // 14: rslbot.api.AdminRevokeLicense.Input
	(*AdminRevokeLicense_Output)(nil),          // 15: rslbot.api.AdminRevokeLicense.Output
	(*AdminSearchDatabase_Input)(nil),          // 16: rslbot.api.AdminSearchDatabase.Input
	(*AdminSearchDatabase_Output)(nil),         // 17: rslbot.api.AdminSearchDatabase.Output
	(*PaymentCreatePayPalCheckout_Input)(nil),  // 18: rslbot.api.PaymentCreatePayPalCheckout.Input
	(*PaymentCreatePayPalCheckout_Output)(nil), // 19: rslbot.api.PaymentCreatePayPalCheckout.Output
	(*ToolStatus_Input)(nil),                   // 20: rslbot.api.ToolStatus.Input
	(*ToolStatus_Output)(nil),                  // 21: rslbot.api.ToolStatus.Output
	(*UserGetLicenses_Input)(nil),              // 22: rslbot.api.UserGetLicenses.Input
	(*UserGetLicenses_Output)(nil),             // 23: rslbot.api.UserGetLicenses.Output
	(*UserGetSession_Input)(nil),               // 24: rslbot.api.UserGetSession.Input
	(*UserGetSession_Output)(nil),              // 25: rslbot.api.UserGetSession.Output
	(*UserLogout_Input)(nil),                   // 26: rslbot.api.UserLogout.Input
	(*UserLogout_Output)(nil),                  // 27: rslbot.api.UserLogout.Output
	(*UserSyncDiscordRole_Input)(nil),          // 28: rslbot.api.UserSyncDiscordRole.Input
	(*UserSyncDiscordRole_Output)(nil),         // 29: rslbot.api.UserSyncDiscordRole.Output
	(rbdb.LicenseKey_Duration)(0),              // 30: rslbot.db.LicenseKey.Duration
	(rbdb.LicenseKey_Tier)(0),                  // 31: rslbot.db.LicenseKey.Tier
	(*rbdb.LicenseKey)(nil),                    // 32: rslbot.db.LicenseKey
	(*rbdb.User)(nil),                          // 33: rslbot.db.User
	(*rbdb.Payment)(nil),                       // 34: rslbot.db.Payment
	(*rbdb.Subscription)(nil),                  // 35: rslbot.db.Subscription
}
var file_proto_rslbot_rbapi_proto_depIdxs = []int32{
	30, // 0: rslbot.api.AdminAddLicenseKey.Input.duration:type_name -> rslbot.db.LicenseKey.Duration
	31, // 1: rslbot.api.AdminAddLicenseKey.Input.tier:type_name -> rslbot.db.LicenseKey.Tier
	32, // 2: rslbot.api.AdminAddLicenseKey.Output.license_key:type_name -> rslbot.db.LicenseKey
	32, // 3: rslbot.api.AdminRevokeLicense.Output.license_key:type_name -> rslbot.db.LicenseKey
	33, // 4: rslbot.api.AdminSearchDatabase.Output.users:type_name -> rslbot.db.User
	32, // 5: rslbot.api.AdminSearchDatabase.Output.license_keys:type_name -> rslbot.db.LicenseKey
	34, // 6: rslbot.api.AdminSearchDatabase.Output.payments:type_name -> rslbot.db.Payment
	35, // 7: rslbot.api.AdminSearchDatabase.Output.subscriptions:type_name -> rslbot.db.Subscription
	30, // 8: rslbot.api.PaymentCreatePayPalCheckout.Input.license_duration:type_name -> rslbot.db.LicenseKey.Duration
	32, // 9: rslbot.api.UserGetLicenses.Output.licenses:type_name -> rslbot.db.LicenseKey
	33, // 10: rslbot.api.UserGetSession.Output.user:type_name -> rslbot.db.User
	10, // 11: rslbot.api.Service.AdminAddLicenseKey:input_type -> rslbot.api.AdminAddLicenseKey.Input
	12, // 12: rslbot.api.Service.AdminGetActiveUsers:input_type -> rslbot.api.AdminGetActiveUsers.Input
	14, // 13: rslbot.api.Service.AdminRevokeLicense:input_type -> rslbot.api.AdminRevokeLicense.Input
	16, // 14: rslbot.api.Service.AdminSearchDatabase:input_type -> rslbot.api.AdminSearchDatabase.Input
	18, // 15: rslbot.api.Service.PaymentCreatePayPalCheckout:input_type -> rslbot.api.PaymentCreatePayPalCheckout.Input
	20, // 16: rslbot.api.Service.ToolStatus:input_type -> rslbot.api.ToolStatus.Input
	22, // 17: rslbot.api.Service.UserGetLicenses:input_type -> rslbot.api.UserGetLicenses.Input
	24, // 18: rslbot.api.Service.UserGetSession:input_type -> rslbot.api.UserGetSession.Input
	26, // 19: rslbot.api.Service.UserLogout:input_type -> rslbot.api.UserLogout.Input
	28, // 20: rslbot.api.Service.UserSyncDiscordRole:input_type -> rslbot.api.UserSyncDiscordRole.Input
	11, // 21: rslbot.api.Service.AdminAddLicenseKey:output_type -> rslbot.api.AdminAddLicenseKey.Output
	13, // 22: rslbot.api.Service.AdminGetActiveUsers:output_type -> rslbot.api.AdminGetActiveUsers.Output
	15, // 23: rslbot.api.Service.AdminRevokeLicense:output_type -> rslbot.api.AdminRevokeLicense.Output
	17, // 24: rslbot.api.Service.AdminSearchDatabase:output_type -> rslbot.api.AdminSearchDatabase.Output
	19, // 25: rslbot.api.Service.PaymentCreatePayPalCheckout:output_type -> rslbot.api.PaymentCreatePayPalCheckout.Output
	21, // 26: rslbot.api.Service.ToolStatus:output_type -> rslbot.api.ToolStatus.Output
	23, // 27: rslbot.api.Service.UserGetLicenses:output_type -> rslbot.api.UserGetLicenses.Output
	25, // 28: rslbot.api.Service.UserGetSession:output_type -> rslbot.api.UserGetSession.Output
	27, // 29: rslbot.api.Service.UserLogout:output_type -> rslbot.api.UserLogout.Output
	29, // 30: rslbot.api.Service.UserSyncDiscordRole:output_type -> rslbot.api.UserSyncDiscordRole.Output
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_rslbot_rbapi_proto_init() }
func file_proto_rslbot_rbapi_proto_init() {
	if File_proto_rslbot_rbapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rslbot_rbapi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rslbot_rbapi_proto_goTypes,
		DependencyIndexes: file_proto_rslbot_rbapi_proto_depIdxs,
		MessageInfos:      file_proto_rslbot_rbapi_proto_msgTypes,
	}.Build()
	File_proto_rslbot_rbapi_proto = out.File
	file_proto_rslbot_rbapi_proto_rawDesc = nil
	file_proto_rslbot_rbapi_proto_goTypes = nil
	file_proto_rslbot_rbapi_proto_depIdxs = nil
}
